// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzk1lihPF9XXX899_ZE7nt5g0UNbcL6Zo',
    appId: '1:534675726580:web:3b3e4b3a60b97b4c0dfea1',
    messagingSenderId: '534675726580',
    projectId: 'movie-app-f25ee',
    authDomain: 'movie-app-f25ee.firebaseapp.com',
    storageBucket: 'movie-app-f25ee.appspot.com',
    measurementId: 'G-ZFX5GD2ZKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqEzPaLmE_ggKtSA5HH7N9mLb839Y_hXw',
    appId: '1:534675726580:android:dac24d6136ca583f0dfea1',
    messagingSenderId: '534675726580',
    projectId: 'movie-app-f25ee',
    storageBucket: 'movie-app-f25ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4ATi62F26vntzhxDsRrgzITCWLU5ty8',
    appId: '1:534675726580:ios:6671315dcf4470cd0dfea1',
    messagingSenderId: '534675726580',
    projectId: 'movie-app-f25ee',
    storageBucket: 'movie-app-f25ee.appspot.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW4ATi62F26vntzhxDsRrgzITCWLU5ty8',
    appId: '1:534675726580:ios:a7cae209abd756230dfea1',
    messagingSenderId: '534675726580',
    projectId: 'movie-app-f25ee',
    storageBucket: 'movie-app-f25ee.appspot.com',
    iosBundleId: 'com.example.movies.RunnerTests',
  );
}
